"""Paper-only Kronos trading research system."""
from .model import (ModelManager, KronosRealPredictor, ModelUnavailableError,
                    DeterministicMockPredictor, REFERENCE_MODEL_NAME,
                    REFERENCE_TOKENIZER_NAME, REFERENCE_MODEL_REVISION,
                    REFERENCE_TOKENIZER_REVISION)
from .pipeline import PredictionPipeline
from .evaluation import (EvaluationConfig, EvaluationRow, EvaluationResult,
                         PredictionEvaluator, compute_metrics, run_evaluation)
from .baselines import (persistence_prediction, previous_direction_prediction,
                        baseline_rows_for, build_model_comparison)
from .robustness import (run_robustness, run_series_robustness,
                         build_consolidated_report, summarize_windows)
from .research_targets import (TargetSpec, TARGET_SPECS, SELECTED_TARGETS,
                               ARCHITECTURE_CHECK, frozen_baseline,
                               frozen_baseline_verified, compute_target_metrics,
                               run_research_experiment)
from .reference_validation import (REFERENCE, run_contract_comparison,
                                   build_validation_report,
                                   upstream_reference_constants)
from .volatility_research import (run_volatility_research, evaluate_success_gate)
from .volatility_baselines import (volatility_forecasts, assign_regime,
                                   har_forecast, ewma_range, rolling_mean_range)
from .classical_volatility import (run_classical_volatility_benchmark,
                                   evaluate_classical_gate,
                                   classify_classical_gate, har_regime_tracking,
                                   recompute_classical_gate,
                                   recompute_classical_summary)
from .ml_volatility import (run_ml_vs_har, build_feature_matrix, run_walk,
                            fit_model, FEATURE_NAMES, evaluate_ml_gate,
                            classify_ml_gate)
from .cross_asset import (run_cross_asset, build_aligned_features,
                          run_walk_ols, evaluate_cross_gate,
                          classify_cross_gate)
from .derivatives_volatility import (run_derivatives_volatility,
                                     build_derivatives_features,
                                     evaluate_derivatives_gate,
                                     classify_derivatives_gate)

__all__ = [
    "ModelManager",
    "KronosRealPredictor",
    "ModelUnavailableError",
    "DeterministicMockPredictor",
    "REFERENCE_MODEL_NAME",
    "REFERENCE_TOKENIZER_NAME",
    "REFERENCE_MODEL_REVISION",
    "REFERENCE_TOKENIZER_REVISION",
    "PredictionPipeline",
    "EvaluationConfig",
    "EvaluationRow",
    "EvaluationResult",
    "PredictionEvaluator",
    "compute_metrics",
    "run_evaluation",
    "persistence_prediction",
    "previous_direction_prediction",
    "baseline_rows_for",
    "build_model_comparison",
    "run_robustness",
    "run_series_robustness",
    "build_consolidated_report",
    "summarize_windows",
    "TargetSpec",
    "TARGET_SPECS",
    "SELECTED_TARGETS",
    "ARCHITECTURE_CHECK",
    "frozen_baseline",
    "frozen_baseline_verified",
    "compute_target_metrics",
    "run_research_experiment",
    "REFERENCE",
    "run_contract_comparison",
    "build_validation_report",
    "upstream_reference_constants",
    "run_volatility_research",
    "evaluate_success_gate",
    "volatility_forecasts",
    "assign_regime",
    "har_forecast",
    "ewma_range",
    "rolling_mean_range",
    "run_classical_volatility_benchmark",
    "evaluate_classical_gate",
    "classify_classical_gate",
    "har_regime_tracking",
    "recompute_classical_gate",
    "recompute_classical_summary",
    "run_ml_vs_har",
    "build_feature_matrix",
    "run_walk",
    "fit_model",
    "FEATURE_NAMES",
    "evaluate_ml_gate",
    "classify_ml_gate",
    "run_cross_asset",
    "build_aligned_features",
    "run_walk_ols",
    "evaluate_cross_gate",
    "classify_cross_gate",
    "run_derivatives_volatility",
    "build_derivatives_features",
    "evaluate_derivatives_gate",
    "classify_derivatives_gate",
]
