-- Kronos Trading System initial PostgreSQL schema

create table if not exists public.ohlcv_raw (
    exchange text not null,
    symbol text not null,
    timeframe text not null,
    timestamp_ms bigint not null,
    timestamp_utc timestamptz not null,
    open double precision not null,
    high double precision not null,
    low double precision not null,
    close double precision not null,
    volume double precision not null,
    source text not null default 'binance_ccxt_public',
    created_at timestamptz not null,

    constraint ohlcv_raw_pkey
        primary key (exchange, symbol, timeframe, timestamp_ms),

    constraint ohlcv_high_gte_low check (high >= low),
    constraint ohlcv_high_gte_open check (high >= open),
    constraint ohlcv_high_gte_close check (high >= close),
    constraint ohlcv_low_lte_open check (low <= open),
    constraint ohlcv_low_lte_close check (low <= close),
    constraint ohlcv_open_positive check (open > 0),
    constraint ohlcv_high_positive check (high > 0),
    constraint ohlcv_low_positive check (low > 0),
    constraint ohlcv_close_positive check (close > 0),
    constraint ohlcv_volume_nonnegative check (volume >= 0)
);

create index if not exists idx_ohlcv_symbol_timeframe_ts
    on public.ohlcv_raw (symbol, timeframe, timestamp_ms);

create table if not exists public.fetch_metadata (
    id bigint generated by default as identity primary key,
    exchange text not null,
    symbol text not null,
    timeframe text not null,
    fetch_start_ms bigint,
    fetch_end_ms bigint,
    candles_fetched bigint,
    candles_inserted bigint,
    duplicates_skipped bigint,
    missing_candles_detected bigint,
    first_timestamp_ms bigint,
    last_timestamp_ms bigint,
    first_timestamp_utc timestamptz,
    last_timestamp_utc timestamptz,
    fetch_duration_s double precision,
    status text,
    error_message text,
    created_at timestamptz not null
);

create index if not exists idx_fetch_meta_symbol_tf
    on public.fetch_metadata (symbol, timeframe, created_at);

create table if not exists public.validation_reports (
    id bigint generated by default as identity primary key,
    exchange text not null,
    symbol text not null,
    timeframe text not null,
    check_type text not null,
    is_valid boolean not null,
    issues_found bigint,
    details jsonb,
    checked_from_ms bigint,
    checked_to_ms bigint,
    created_at timestamptz not null
);
